from fastapi import APIRouter, Depends, HTTPException, Query, status
from app.services.supabase import get_current_user, supabase
from app.services.gemini import generate_speaking_topics, TopicListResponse

router = APIRouter()


@router.get("/generate", response_model=TopicListResponse)
def generate_topic(
    category: str = Query("impromptu", description="Speaking category (e.g. impromptu, interview, persuasive, warmup)"),
    difficulty: str = Query("medium", description="Difficulty level (e.g. easy, medium, hard)"),
    current_user: dict = Depends(get_current_user),
) -> TopicListResponse:
    """
    Generates a new coaching topic prompt using Gemini, saves the generated topic
    to the Supabase database under the user's ID, and returns the response.
    """
    # 1. Generate structured topic using Gemini
    topic_list = generate_speaking_topics(category=category, difficulty=difficulty, count=1)

    if not topic_list.topics:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="No topics were generated by the AI service."
        )

    # 2. Persist the generated topic in the database
    for topic in topic_list.topics:
        try:
            db_data = {
                "user_id": current_user["id"],
                "category": category,
                "difficulty": difficulty,
                "title": topic.title,
                "prompt": topic.prompt,
                "context": topic.context,
                "suggested_points": topic.suggested_points,
            }
            
            # Execute database insert
            response = supabase.table("topics").insert(db_data).execute()
            
            if not response.data:
                raise Exception("Empty database insert response data")
        except Exception as e:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Failed to persist topic to database: {str(e)}"
            )

    return topic_list
